name: CD

on:
  push:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: restore cargo cache
      uses: actions/cache@v2
      env:
        cache-name: ci
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          ~/.cargo/bin
          target
        key: ubuntu-latest-${{ env.cache-name }}-nightly-${{ hashFiles('Cargo.lock') }}

    - name: install mingw
      run: sudo apt-get update && sudo apt-get -y install --no-install-recommends mingw-w64

    - name: add windows target
      run: rustup target add x86_64-pc-windows-gnu

    - name: install rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        profile: minimal
        components: rustfmt, clippy

    - name: targets list
      run: rustup target list | grep installed

    - name: build release linux
      id: build-linux-release
      if: success()
      run: make build-release-linux-musl

    - name: build release windows
      id: build-windows-release
      if: success()
      run: make build-release-win

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ./release/win/trackrs.exe
          ./release/linux-gnu/trackrs
