name: CD

on:
  push:
    branches: [ main ]
    paths: [ src/** ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: restore cargo cache
      uses: actions/cache@v4
      env:
        cache-name: ci
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          ~/.cargo/bin
          target
        key: self-hosted-${{ env.cache-name }}-nightly-${{ hashFiles('Cargo.lock') }}

    - name: install rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        profile: minimal
        components: rustfmt, clippy

    - name: targets list
      run: rustup target list | grep installed

    - name: prepare scripts
      if: success()
      run: chmod +x ${{ github.workspace }}/eng/set-version.sh && chmod +x ${{ github.workspace }}/eng/build-release.sh

    - name: build release linux
      id: build-linux-release
      if: success()
      run: make build-release-linux-musl

    - name: build release windows
      id: build-windows-release
      if: success()
      run: make build-release-win

    # # - name: build release mac
    # #   id: build-mac-release
    # #   if: ${{ steps.semantic-version.outputs.new_release_published == 'true' }}
    # #   run: make build-release-mac

    - name: publish release
      uses: cycjimmy/semantic-release-action@v4
      if: success()
      with:
        dry_run: false
        extra_plugins: |
          @semantic-release/changelog@6
          @semantic-release/git@10
          @semantic-release/github@8
          @semantic-release/commit-analyzer@9
          @semantic-release/exec@6
          conventional-changelog-conventionalcommits@4
      env:
        GITHUB_TOKEN: ${{ secrets.SEMREL }}
