name: CI

on:
  push:
    branches: [ dev, test ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: restore cargo cache
      uses: actions/cache@v2
      env:
        cache-name: ci
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          ~/.cargo/bin
          target
        key: ubuntu-latest-${{ env.cache-name }}-nightly-${{ hashFiles('Cargo.lock') }}

    - name: install rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        profile: minimal
        components: rustfmt, clippy

    - name: build
      id: build
      if: success()
      run: make build

    - name: run tests
      id: test
      if: success()
      run: make test
