name: Prepare-Release

on:
  push:
    branches: [ main, test ]

env:
  CARGO_TERM_COLOR: always

jobs:
  semrel:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: prepare scripts
      if: success()
      run: chmod +x ${{ github.workspace }}/eng/set-version.sh

    - name: publish release
      uses: cycjimmy/semantic-release-action@v2
      if: success()
      with:
        semantic_version: 18
        dry_run: false
        extra_plugins: |
          @semantic-release/changelog@6
          @semantic-release/git@10
          @semantic-release/commit-analyzer@9
          @semantic-release/exec@6
          conventional-changelog-conventionalcommits@4
      env:
        GITHUB_TOKEN: ${{ secrets.SEMREL }}
